### PR TITLE
Prepare for v1.0.4

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

### CODE REVIEW

**Comment by dmsimard** [comment]
@NilashishC this wasn't ready in time for the rebuild of ansible 6.0.0a2 but do please let us know when it's out so we can include it in the next release.

**Comment by NilashishC** [comment]
@dmsimard Sure. Looks like CI hasn't started even now on this.

cc @GomathiselviS @goneri @komaldesai13 could you please help?

**Comment by justjais** [comment]
regate

**Review by justjais — COMMENTED** [review]
@NilashishC `.plugin-cache.yaml ` is required?

**Review by justjais — APPROVED** [review]

**Comment by NilashishC** [comment]
@justjais Yep, afaiu it helps the antsibull-changelog tool to run faster the next time.

**Pull request merged**
