### PR TITLE
Update README: freenode -> libera.chat

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-community/community-topics/issues/19

### CODE REVIEW

**Comment by Andersson007** [comment]
recheck

**Comment by NilashishC** [comment]
@pabelanger @GomathiselviS This is failing with:
https://8222f1077c05726a7e78-97e6cb0e04fa5e79735f25a0e6bdd526.ssl.cf2.rackcdn.com/37/52228bf97a4aaed2b94b6685f0431c9cee4602ca/check/ansible-test-units-frr-python27/557ac06/job-output.html#l978

**Comment by GomathiselviS** [comment]
> @pabelanger @GomathiselviS This is failing with:
> https://8222f1077c05726a7e78-97e6cb0e04fa5e79735f25a0e6bdd526.ssl.cf2.rackcdn.com/37/52228bf97a4aaed2b94b6685f0431c9cee4602ca/check/ansible-test-units-frr-python27/557ac06/job-output.html#l978

@NilashishC Adding `black ; python_version > '3.5'` to test-requirements.txt will fix the issue.

**Comment by Andersson007** [comment]
thanks everyone!

**Pull request merged**
